#!/bin/sh

testplan=$1
filename=$2

touch $filename.tmp
echo "going_to_run_test_plan $testplan" > $filename.tmp
jmeter_output=$(jmeter -n -t $testplan -l /tmp/jmeter_samples.log -j /tmp/jmeter.log -Jjmeterengine.nongui.port=0 -Jsummariser.name=summary -Jsummariser.interval=100 -Jsummariser.out=true)
$jmeter_output >> $filename.tmp
mv $filename.tmp $filename.fnsh
