#!/bin/sh

# This requires jmeter

# define variables
plans_dir="../jmeter_plans"


iterate_testplans()
{
    touch running.txt
    for file in $plans_dir/*
    do
        run_jmeter $file
    done
    rm running.txt
    mv finished.tmp finished.txt

}

run_jmeter()
{
    testplan=$1
    echo "going_to_run_test_plan $testplan"
    jmeter_output=$(jmeter -n -t $testplan -l /tmp/jmeter_samples.log -j /tmp/jmeter.log -Jsummariser.name=summary -Jsummariser.interval=100 -Jsummariser.out=true)
    echo $jmeter_output
}

# check if jmeter for testplans is already running by checking if file running.txt exists
is_running()
{
    if [ -f running.txt ]; then
        return 0
    else
        return 1
    fi
}

# check if jmeter testplans are finished, by checking if file finished.txt exists
is_finished()
{
    if [ -f finished.txt ]; then
        return 0
    else
        return 1
    fi
}

#main routine

if which jmeter > /dev/null; then
    if [ -d "$plans_dir" ]; then
        echo "<<<jmeter>>>"
    fi


    if is_running $1; then
        #iteration of testplans is still running, we can skip
        echo "exit script here"
        exit 0;
    else
        if is_finished $1; then
            #testplans are finished
            cat finished.txt
            rm finished.txt
            iterate_testplans > finished.tmp &
            exit 0;
        else
            #need to start testplan interation
            iterate_testplans > finished.tmp &
            #mv finished.tmp finished.txt
            #rm finished.tmp
            exit 0;
        fi
    fi
fi




#Created the tree successfully using /Users/hpl cher/develop/BRK/project/jmeter/BRK-live.jmx
#Starting the test @ Wed Jul 13 12:12:38 CEST 2011 (1310551958181)
#Tidying up ...    @ Wed Jul 13 12:13:20 CEST 2011 (1310552000736)
#... end of run
