#!/bin/sh

#: Title       : jmeter
#: Date Created: Thu Jul 14 17:54:21 CET 2011
#: Last Edit   : Thu Jul 14 17:54:21 CET 2011
#: Author      : Daniel Altiparmak <daniel.altiparmak@inquant.de>
#: Version     : 1.00
#: Description : Shell Script running JMeter Testplans for Nagios evaluation
#: Options     : xxx
#: Note        : This script requiers JMeter to be installed

# define variables
plans_dir="../jmeter_plans"
DIRECTORY=$(cd `dirname $0` && pwd)

# function      : iterate_testplans() 
# description   : iterates over all testplans in plans_dir and runs jmeter
#                 loop is controlled by running.txt
iterate_testplans()
{
    touch running.txt
    for file in $plans_dir/*
    do
        run_jmeter $file
    done
}

# function     : run_jmeter()
# parameter    : $file
# description  : runs JMeter background process for testplan
run_jmeter()
{
    testplan=$1
    filename=`basename $testplan`
    $DIRECTORY/jmeter_runner $testplan $filename &
}

# check if jmeter for testplans is already running by checking if file running.txt exists
# function     : is_running()
# description  : check if jmeter for testplans is already running by verifying if file running.txt exists
is_running()
{
    if [ -f running.txt ]; then
        #echo "running.txt exists"
        return 0 #returncode true => is running
    else
        #echo "no running.txt exists"
        return 1 # returncode false => is not running
    fi
}

# function     : is_finished()
# description  : check if jmeter testplans are finished, by checking if file finished.txt exists
is_finished()
{
    # if any tmp files exist, a tesptlan is still running
    if [ -e *.tmp ]; then
        #echo "tmp file exists, plans are running"
        return 1 # returncode true => is not finished
    else
        return 0 # returncode false => is finished
    fi
}


#main routine
if which jmeter > /dev/null; then
    
    if is_running $1; then
        if is_finished $1; then
            #echo "is finished"
            #echo "we cann remove running.txt"
            cat *.fnsh > output.txt
            rm *.fnsh
            rm running.txt
            echo "<<<jmeter>>>"
            cat output.txt
        else
            echo "<<<jmeter>>>"
            if [ -f output.txt ]; then
                cat output.txt
            fi
        fi
    else
        
        if [ -f output.txt ]; then
            echo "<<<jmeter>>>"
            cat output.txt
        fi

        iterate_testplans
        exit 0;
    fi
fi
